force-app/main/default/objects/Aeropuerto__c/Aeropuerto__c.object-meta.xml
<CustomObject>
    <description>Un aeropuerto es una locación física que está acondicionado para recibir y despachar vuelos en diferentes ciudades</description>
    <label>Aeropuerto</label>
    <nameField>
        <label>Nombre del aeropuerto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aeropuertos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Aeropuerto__c/fields/C_digo_IATA__c.field-meta.xml
<CustomField>
    <fullName>C_digo_IATA__c</fullName>
    <description>El código de aeropuertos de IATA está formado por grupos de tres letras, que designan a cada aeropuerto del mundo</description>
    <label>Código IATA</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Avion__c/Avion__c.object-meta.xml
<CustomObject>
    <description>Un avión es un artefacto de transporte de pasajeros o carga. Si el avión es de tipo carga no se debe admitir número de pasajeros.</description>
    <label>Avion</label>
    <nameField>
        <label>TIpo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aviones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Avion__c/fields/N_mero_de_pasajeros_clase_negocios__c.field-meta.xml
<CustomField>
    <fullName>N_mero_de_pasajeros_clase_negocios__c</fullName>
    <description>Número de pasajeros clase negocios con los que cuenta el avión</description>
    <label>Número de pasajeros clase negocios</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avion__c/fields/N_mero_de_pasajeros_clase_turista__c.field-meta.xml
<CustomField>
    <fullName>N_mero_de_pasajeros_clase_turista__c</fullName>
    <description>Número de pasajeros clase turista con los cuenta el avión</description>
    <label>Número de pasajeros clase turista</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tripulacion__c/Tripulacion__c.object-meta.xml
<CustomObject>
    <description>Objeto que relaciona auxiliares de vuelo(contacto) con vuelos</description>
    <label>Tripulacion</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Nombre de Tripulacion</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tripulaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tripulacion__c/fields/Contacto__c.field-meta.xml
<CustomField>
    <fullName>Contacto__c</fullName>
    <description>Relación con el objeto contacto para los auxiliares</description>
    <label>Contacto</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Auxiliar de vuelo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tripulaciones</relationshipLabel>
    <relationshipName>Tripulaciones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tripulacion__c/fields/Vuelo__c.field-meta.xml
<CustomField>
    <fullName>Vuelo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo que se relaciona con el vuelo correspondiente</description>
    <label>Vuelo</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Tripulaciones</relationshipLabel>
    <relationshipName>Tripulaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TripulacionRequeridaTest.cls
@isTest
public class TripulacionRequeridaTest {
 
    @TestSetup
    static void makeData(){
        Contact auxiliar = new contact(LastName = 'Juan', Nacionalidad__c = 'alemán', 
                                       Tipo_de_identificacion__c = 'Cédula de Ciudadania', Numero_de_identificacion__c = '23456', RecordTypeId = '0128a000000UxlbAAC');
        Contact auxiliar2 = new contact(LastName = 'Marta', Nacionalidad__c = 'alemán', 
                                       Tipo_de_identificacion__c = 'Cédula de Ciudadania', Numero_de_identificacion__c = '9566846', RecordTypeId = '0128a000000UxlbAAC');
        
        insert auxiliar;
        insert auxiliar2;
        Avion__c avion = new Avion__c(N_mero_de_pasajeros_clase_negocios__c = 20, N_mero_de_pasajeros_clase_turista__c = 20, Name  ='Airbus A330');
        insert avion;
        Aeropuerto__c aeropuerto1 = new Aeropuerto__c(name = 'prueba1', C_digo_IATA__c = 'AAA');
        Aeropuerto__c aeropuerto2 = new Aeropuerto__c(name = 'prueba2', C_digo_IATA__c = 'BBB');
        Product2 vuelo = new Product2(Name = 'AV-0001',
                                 Avion__c = avion.Id,
                                 Fecha_y_hora_de_partida__c = datetime.now()+8/7,
                                 Fecha_y_hora_estimada_de_llegada__c = (datetime.now()+8/7).addHours(1),
                                 Aeropuerto_de_partida__c = aeropuerto1.Id,
                                 Aeropuerto_de_llegada__c = aeropuerto2.id,
                                 IsActive = true,
                                 Estado__c = 'En venta');
        insert vuelo;
        Tripulacion__C tripulante = new Tripulacion__c(Contacto__c = auxiliar.id, Vuelo__c = vuelo.id);
        insert tripulante;
        
    }

    @isTest
    private static void obtieneUnVuelo(){
        
        
            List<TripulacionRequerida.vuelo> vuelos = TripulacionRequerida.obtenerVuelos();
       		System.assertEquals(1, vuelos.size());
    }

    @isTest
    private static void obtieneMuchosVuelos(){
        List<Product2> lista = new List<Product2>();
        Aeropuerto__c aeropuerto1 = new Aeropuerto__c(name = 'prueba1', C_digo_IATA__c = 'AAA');
        Aeropuerto__c aeropuerto2 = new Aeropuerto__c(name = 'prueba2', C_digo_IATA__c = 'BBB');
        Avion__c avion = new Avion__c(N_mero_de_pasajeros_clase_negocios__c = 20, N_mero_de_pasajeros_clase_turista__c = 20, Name  ='Airbus A330');
        insert avion;
        for(integer i = 0; i < 199; i++){
            Product2 vuelos = new Product2(Name = 'AV-10'+ i,
                                Avion__c = avion.Id,
                                Fecha_y_hora_de_partida__c = datetime.now()+2,
                                Fecha_y_hora_estimada_de_llegada__c = (datetime.now()+2).addHours(1),
                                Aeropuerto_de_partida__c = aeropuerto1.Id,
                                 Aeropuerto_de_llegada__c = aeropuerto2.id,
                                IsActive = true,
                                Estado__c = 'En venta');
            lista.add(vuelos);
        }
        insert lista;
        Test.startTest();
        try{
            List<TripulacionRequerida.vuelo> pruebaVuelos = TripulacionRequerida.obtenerVuelos(); 
        	System.assertEquals(200, pruebaVuelos.size());
        }catch(exception e){
            
        }
        Test.stopTest();
        
    }
    
    @isTest
    private static void obtenerAuxiliaresTest(){
            List<Product2> vuelo = [select id from Product2 limit 1];
            for(Product2 v: vuelo){
                List<TripulacionRequerida.opcion> lista= TripulacionRequerida.opcion.getAuxiliares(v.id);
                System.assertEquals(3, lista.size());
            }
    }
    
    @isTest
    private static void saveAuxiliaresTest(){
        List<Contact> auxiliares = [Select id from contact limit 2];
        List<String> ids = new List<String>();
        for(Contact c: auxiliares){
            ids.add(c.id);
        }
        
        List<product2> vuelo = [select id from product2 limit 1];
        for(Product2 v: vuelo){
            TripulacionRequerida.saveAuxiliares(ids, v.id);
        }
        
        for(Product2 v: vuelo){
            List<TripulacionRequerida.opcion> lista= TripulacionRequerida.opcion.getAuxiliares(v.id);
            System.assertEquals(4, lista.size());
        }
    }
    
    private static void exceptionObtenerVuelos(){
        List<Avion__c> avion = [select id from avion__c limit 1];
        delete avion;
        
        try{
            List<TripulacionRequerida.vuelo> vuelos = TripulacionRequerida.obtenerVuelos();
            
        }catch(Exception e){
            List<avion__c> vuelos = [Select id from avion__c limit 1]; 
       		System.assertEquals(1, vuelos.size());
        }
        
    }
}