force-app/main/default/objects/Aeropuerto__c/Aeropuerto__c.object-meta.xml
<CustomObject>
    <description>Un aeropuerto es una locación física que está acondicionado para recibir y despachar vuelos en diferentes ciudades</description>
    <label>Aeropuerto</label>
    <nameField>
        <label>Nombre del aeropuerto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aeropuertos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Aeropuerto__c/fields/C_digo_IATA__c.field-meta.xml
<CustomField>
    <fullName>C_digo_IATA__c</fullName>
    <description>El código de aeropuertos de IATA está formado por grupos de tres letras, que designan a cada aeropuerto del mundo</description>
    <label>Código IATA</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Aeropuerto__c/fields/Ciudad__c.field-meta.xml
<CustomField>
    <fullName>Ciudad__c</fullName>
    <description>Lista de selección de ciudades dependiente de la lista de selección de paises</description>
    <label>Ciudad</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Pais__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Bamiyán</fullName>
            </value>
            <value>
                <fullName>Bagram</fullName>
            </value>
            <value>
                <fullName>Lashkar Gah</fullName>
            </value>
            <value>
                <fullName>Fayzabad</fullName>
            </value>
            <value>
                <fullName>Herat</fullName>
            </value>
            <value>
                <fullName>Jalalabad</fullName>
            </value>
            <value>
                <fullName>Kabul</fullName>
            </value>
            <value>
                <fullName>Kandahar</fullName>
            </value>
            <value>
                <fullName>Mazar-e Sarif</fullName>
            </value>
            <value>
                <fullName>Colonia, Bonn</fullName>
            </value>
            <value>
                <fullName>Fráncfort del Meno</fullName>
            </value>
            <value>
                <fullName>Hannover</fullName>
            </value>
            <value>
                <fullName>Hamburgo</fullName>
            </value>
            <value>
                <fullName>Heligoland</fullName>
            </value>
            <value>
                <fullName>Fráncfort</fullName>
            </value>
            <value>
                <fullName>Munich</fullName>
            </value>
            <value>
                <fullName>Berlín</fullName>
            </value>
            <value>
                <fullName>Luanda</fullName>
            </value>
            <value>
                <fullName>Riad</fullName>
            </value>
            <value>
                <fullName>Buenos Aires</fullName>
            </value>
            <value>
                <fullName>San Rafael</fullName>
            </value>
            <value>
                <fullName>Paso de los Libres</fullName>
            </value>
            <value>
                <fullName>San Carlos de Bariloche</fullName>
            </value>
            <value>
                <fullName>Córdoba</fullName>
            </value>
            <value>
                <fullName>Clorinda</fullName>
            </value>
            <value>
                <fullName>Ciudad de Corrientes</fullName>
            </value>
            <value>
                <fullName>Concordia</fullName>
            </value>
            <value>
                <fullName>San Fernando del Valle de Catamarca</fullName>
            </value>
            <value>
                <fullName>Ezeiza</fullName>
            </value>
            <value>
                <fullName>San Fernando</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Aeropuerto__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <description>País donde se encuentra ubicado el aeropuerto</description>
    <label>País</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afganistán</fullName>
            </value>
            <value>
                <fullName>Alemania</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Arabia Saudita</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bangladés</fullName>
            </value>
            <value>
                <fullName>Bélgica</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Brasil</fullName>
            </value>
            <value>
                <fullName>Canadá</fullName>
            </value>
            <value>
                <fullName>Catar</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Chipre</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
                <default>true</default>
                <label>Colombia</label>
            </value>
            <value>
                <fullName>Corea del Sur</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Croacia</fullName>
            </value>
            <value>
                <fullName>Cuba</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>El Salvador</fullName>
            </value>
            <value>
                <fullName>Emiratos Árabes Unidos</fullName>
            </value>
            <value>
                <fullName>España</fullName>
            </value>
            <value>
                <fullName>Estados Unidos</fullName>
            </value>
            <value>
                <fullName>Finlandia</fullName>
            </value>
            <value>
                <fullName>Francia</fullName>
            </value>
            <value>
                <fullName>Grecia</fullName>
            </value>
            <value>
                <fullName>Guatemala</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Avion__c/Avion__c.object-meta.xml
<CustomObject>
    <description>Un avión es un artefacto de transporte de pasajeros o carga. Si el avión es de tipo carga no se debe admitir número de pasajeros.</description>
    <label>Avion</label>
    <nameField>
        <label>TIpo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aviones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Avion__c/fields/N_mero_de_pasajeros_clase_negocios__c.field-meta.xml
<CustomField>
    <fullName>N_mero_de_pasajeros_clase_negocios__c</fullName>
    <description>Número de pasajeros clase negocios con los que cuenta el avión</description>
    <label>Número de pasajeros clase negocios</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avion__c/fields/N_mero_de_pasajeros_clase_turista__c.field-meta.xml
<CustomField>
    <fullName>N_mero_de_pasajeros_clase_turista__c</fullName>
    <description>Número de pasajeros clase turista con los cuenta el avión</description>
    <label>Número de pasajeros clase turista</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestBatchAsignarTripulacion.cls
@isTest
public class TestBatchAsignarTripulacion {
	@testSetup
    static void setup(){
        datetime fechaPartida = datetime.now();
        datetime fechaLlegada = datetime.now();
        //AVION
        Avion__c avion = new Avion__c(Name = 'Airbus A330', N_mero_de_pasajeros_clase_turista__c = 20, N_mero_de_pasajeros_clase_negocios__c = 20);
        insert avion;
        
        //AEROPUERTO
        list<Aeropuerto__c> aeropuertos = new List<Aeropuerto__c>();
        for(integer i = 0 ; i < 2; i++){
            Aeropuerto__c aeropuerto = new Aeropuerto__c(C_digo_IATA__c = 'AAA', Name='aeropuerto'+i , Pais__c = 'Colombia', Ciudad__c = 'Antioquia');
            aeropuertos.add(aeropuerto);
        }
        insert aeropuertos;
        
        //VUELO
        Product2 vuelo = new Product2(Name = 'AE-0001', Avion__c = avion.id, Estado__c = 'En venta', fecha_y_hora_de_partida__c = fechaPartida.addDays(7),
                                       Fecha_y_hora_real_de_llegada__c = fechaLlegada.addDays(8),Aeropuerto_de_partida__c =aeropuertos[0].id, 
                                      Aeropuerto_de_llegada__c = aeropuertos[1].id, IsActive = true);
        insert vuelo;
    }
    
    @isTest
    public static void encontrarVuelos(){
        Test.startTest();
        BatchAsignarTripulacion batch = new BatchAsignarTripulacion();
        Id batchId = Database.executeBatch(batch);
        Test.stopTest();
        List<Product2> vuelo = [Select id from Product2];
        
        System.assertEquals(1, vuelo.size());    
    }
}