force-app/main/default/objects/Aeropuerto__c/Aeropuerto__c.object-meta.xml
<CustomObject>
    <description>Un aeropuerto es una locación física que está acondicionado para recibir y despachar vuelos en diferentes ciudades</description>
    <label>Aeropuerto</label>
    <nameField>
        <label>Nombre del aeropuerto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aeropuertos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clima__c/Clima__c.object-meta.xml
<CustomObject>
    <description>El clima es el registro de las condiciones climáticas para un aeropuerto en un momento determinado, esta información es guardada para cada vuelo 24 horas antes de ser realizado</description>
    <label>Clima</label>
    <nameField>
        <displayFormat>C-{000}</displayFormat>
        <label>Clima Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clima</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clima__c/fields/Aeropuerto__c.field-meta.xml
<CustomField>
    <fullName>Aeropuerto__c</fullName>
    <description>informacion del aeropuerto donde se registra el clima</description>
    <label>Aeropuerto</label>
    <referenceTo>Aeropuerto__c</referenceTo>
    <relationshipLabel>Clima</relationshipLabel>
    <relationshipName>Clima</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clima__c/fields/Fecha_y_hora_de_prediccion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_hora_de_prediccion__c</fullName>
    <description>Fecha y hora de prediccion de clima en el aeropuerto</description>
    <label>Fecha y hora de prediccion</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Clima__c/fields/Temperatura__c.field-meta.xml
<CustomField>
    <fullName>Temperatura__c</fullName>
    <description>Numero de temperatura a la que se encuentra el aeropuerto</description>
    <label>Temperatura</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Clima__c/fields/Unidad__c.field-meta.xml
<CustomField>
    <fullName>Unidad__c</fullName>
    <description>Unidad de medida en la que fue tomada la temperatura en el aeropuerto</description>
    <label>Unidad</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Centigrados</fullName>
            </value>
            <value>
                <fullName>Fahrenheit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClimaRest.cls
public class ClimaRest {
    public static clima__c llamadaOpenweather(decimal latitud, decimal longitud, string idAeropuerto){
        Clima__c climas;
        string codigoApi = '0e64d11255d835cdac09ee7ba5cc53b5';
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('https://api.openweathermap.org/data/2.5/weather?lat='+latitud+'&lon='+longitud+'&appid='+ codigoApi +'&units=metric');
        request.setMethod('GET');
        HttpResponse response = http.send(request);
        if(response.getStatusCode() == 200){
            Map<String, Object> results = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
            Map<String, Object> clima = (Map<String, Object>) results.get('main'); 
            climas = new Clima__c(Temperatura__c = (Decimal)clima.get('temp'), Unidad__c = 'Centigrados', Aeropuerto__c = idAeropuerto, Fecha_y_hora_de_prediccion__c = datetime.now());
        }
        return climas;
    }
}